controller_list:
  - name: fake_franka_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: fake_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - ewellix_lift_top_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - panda_finger_joint1
  - name: fake_arm_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - ewellix_lift_top_joint
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
initial:  # Define initial robot poses.
  - group: franka_arm
    pose: arm_default